### SVD - розклад

In [11]:
import numpy as np
from scipy import linalg

In [25]:
# дані для тестування
def test_0():
    matrix = [[1., 0., 0., 0., 2.], [0., 0., 3., 0., 0.], [0., 0., 0., 0., 0.], [0., 2., 0., 0., 0.]]
    b = [10.929, -0.7786, 0.012169, -2.4413]
    return np.array(matrix), np.array(b)

def test_1():
    matrix = [[0.41585, -0.35891, -0.63151, 0.48148], [1.3936, 1.2212, -2.1488, 1.6136], 
              [-0.87625, 0.73761, 1.2978, -1.0145], [-4.8377, -4.2394, 7.4592, -5.6012]]
    b = [2.8763, -3.3795, -2.1987, -1.2131]
    return np.array(matrix), np.array(b)

def test_2():
    matrix = [[0.41585, -0.35891, -0.63151, 0.48148], [1.3936, 1.2212, -2.1488, 1.6136], 
              [-0.87625, 0.73761, 1.2978, -1.0145], [-4.8377, -4.2394, 7.4592, -5.6012]]
    b = [10.929, -0.7786, 0.012169, -2.4413]
    return np.array(matrix), np.array(b)

In [29]:
A_1, b_1 = test_1()
#A_test = test_0()
U, s, Vh = linalg.svd(A_1)
V = np.transpose(Vh)
sigma_matrix = np.diag(s) 
egin_val_not_null = np.array([x for x in s if (x != 0)]) # ненульові власні числа
rank = len(egin_val_not_null)
cond = egin_val_not_null.max() / egin_val_not_null.min()

In [30]:
def solve_simple_system(s, Vh, rank):
    x = []
    if (rank == len(s)):
        x = [0 for i in range(len(s))]
    else:
        for i in range((rank+1), Vh.shape[1]):
            x.append(Vh[:][i])            
    return x


In [31]:
print('The initial matrix \n {}'.format(A_1))
print('The initial vector b \n {}'.format(b_1.reshape(-1, 1)))
print('\n')
print('The singular factorization')
print('U: \n {}'.format(U))
print('S: \n {}'.format(sigma_matrix))
print('V: \n {}'.format(Vh))
print('\n')
print('The rank of the matrix is {}'.format(rank))
print('\n')
print('The conditional number of the matrix is {}'.format(cond))
print('\n')
print('The solution of the simple system: Ax = 0')
print('\n')
x_sol = solve_simple_system(s, V, rank)
if (len(x_sol) == len(s)):
    print('The system has only zero solution')
else:
    print('The solution of the system is ')
    for k in range(len(x_sol)):
        print('{} {}'.format(('c_' + str(k) + ' * '), x_sol[k]))
    print('c_i = const')
    #print('The error of the solution {}'.format())
print('\n')

print('The solution of the general system: Ax = b')
print('\n')
# розв'язок неоднорідної системи
U_T = np.transpose(U)
z = U_T.dot(b_1)
if (rank == V.shape[1]):
        y = z / egin_val_not_null
        x = V.dot(y)
        print('The system has one solution \n {}'.format(x.reshape(-1, 1)))
        print('The error of the solution {}'.format(A_1.dot(x) - b_1))
        print('The solution with the library \n {}'.format((np.linalg.solve(A_1, b_1)).reshape(-1, 1)))
else:
    counter = 0
    for k in range((rank+1), len(z)):
        if (z[k] != 0):
            counter += 1
    if (counter == 0):
        y = np.zeros(V.shape[1])
        for i in range(rank):
            y[i] = z[i] / egin_val_not_null[i]
        print('The solution of the system is a combination of the solution Ax = 0 and the partial solution of Ax = b')
        print('The partial solution of Ax = b  is \n {}'.format((V.dot(y)).reshape(-1, 1)))
        print('The error of the partial solution is {}'.format(A_1.dot(V.dot(y)) - b_1))
        print('The solution of Ax = 0 is ')
        for n in range((rank+1), V.shape[1]):
            print('{} {}'.format(('c_' + str(n) + ' * '), V[:][n]))
    else:
        print('The system has only psevdosolution \n {}'.format((V.dot(y)).reshape(-1, 1)))
        print('The error of the solution {}'.format(A_1.dot(V.dot(y)) - b_1))


The initial matrix 
 [[ 0.41585 -0.35891 -0.63151  0.48148]
 [ 1.3936   1.2212  -2.1488   1.6136 ]
 [-0.87625  0.73761  1.2978  -1.0145 ]
 [-4.8377  -4.2394   7.4592  -5.6012 ]]
The initial vector b 
 [[ 2.8763]
 [-3.3795]
 [-2.1987]
 [-1.2131]]


The singular factorization
U: 
 [[-5.95435766e-02  4.31071269e-01 -9.00350369e-01  1.15624585e-03]
 [-2.74177941e-01 -3.80885049e-02  1.13038130e-03  9.60923745e-01]
 [ 1.24194966e-01 -8.91744316e-01 -4.35163559e-01  6.01726438e-04]
 [ 9.51765007e-01  1.32358988e-01  7.82722623e-04  2.76810145e-01]]
S: 
 [[1.19032496e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.52110356e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.01824212e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.64218151e-05]]
V: 
 [[-4.30137583e-01 -3.57613307e-01  6.62620880e-01 -4.98024047e-01]
 [ 1.75700549e-01 -9.33606186e-01 -2.36929859e-01  2.03403660e-01]
 [ 4.60606502e-01  2.21858679e-02  7.10490789e-01  5.3