### SVD - розклад

In [1]:
import numpy as np
from scipy import linalg

In [2]:
# дані для тестування
def test_0():
    matrix = [[1., 0., 0., 0., 2.], [0., 0., 3., 0., 0.], [0., 0., 0., 0., 0.], [0., 2., 0., 0., 0.]]
    return np.array(matrix)

def test_1():
    matrix = [[0.41585, -0.35891, -0.63151, 0.48148], [1.3936, 1.2212, -2.1488, 1.6136], 
              [-0.87625, 0.73761, 1.2978, -1.0145], [-4.8377, -4.2394, 7.4592, -5.6012]]
    b = [2.8763, -3.3795, -2.1987, -1.2131]
    return np.array(matrix), np.array(b)

def test_2():
    matrix = [[0.41585, -0.35891, -0.63151, 0.48148], [1.3936, 1.2212, -2.1488, 1.6136], 
              [-0.87625, 0.73761, 1.2978, -1.0145], [-4.8377, -4.2394, 7.4592, -5.6012]]
    b = [10.929, -0.7786, 0.012169, -2.4413]
    return np.array(matrix), np.array(b)

In [3]:
A_1, b_1 = test_1()
A_test = test_0()
U, s, Vh = linalg.svd(A_test)
V = np.transpose(Vh)
sigma_matrix = np.diag(s) 
egin_val_not_null = np.array([x for x in s if (x != 0)]) # ненульові власні числа
rank = len(egin_val_not_null)
cond = egin_val_not_null.max() / egin_val_not_null.min()

In [4]:
def solve_simple_system(s, Vh, rank):
    x = []
    if (rank == len(s)):
        x = [0 for i in range(len(s))]
    else:
        for i in range((rank+1), Vh.shape[1]):
            x.append(Vh[:][i])            
    return x
    

In [7]:
print('The initial matrix \n {}'.format(A_1))
print('The initial vector b \n {}'.format(b_1))
print('\n')
print('The singular factorisation')
print('U: \n {}'.format(U))
print('S: \n {}'.format(sigma_matrix))
print('V: \n {}'.format(V))
print('\n')
print('The rank of the matrix is {}'.format(rank))
print('\n')
print('The conditional number of the matrix is {}'.format(cond))
print('\n')
print('The solution of the simple system: Ax = 0')
print('\n')
x_sol = solve_simple_system(s, Vh, rank)
if (len(x_sol) == len(s)):
    print('The system has only zero solution')
else:
    print('The solution of the system is a linear combination of vectors')
    for k in range(len(x_sol)):
        print(x_sol[k].reshape(len(x_sol[k]), 1))
print('\n')

print('The solution of the general system: Ax = b')
print('\n')
# розв'язок неоднорідної системи
U_T = np.transpose(U)
z = U_T.dot(b_1)
if (rank == Vh.shape[1]):
        y = z / egin_val_not_null
        x = Vh.dot(y)
        print('The system has one solution \n {}'.format(x))
else:
    counter = 0
    for k in range((rank+1), len(z)):
        if (z[k] != 0):
            counter += 1
    if (counter == 0):
        y = np.zeros(Vh.shape[1])
        for i in range(rank):
            y[i] = z[i] / egin_val_not_null[i]
        print('The solution of the system is a combination of the solution Ax = 0 and the partial solution of Ax = b')
        print('The partial solution of Ax = b  is {}'.format(Vh.dot(y)))
        print('The solution of Ax = 0 is the linear combination of vectors')
        for n in range((rank+1), Vh.shape[1]):
            print(Vh[:][n])


The initial matrix 
 [[ 0.41585 -0.35891 -0.63151  0.48148]
 [ 1.3936   1.2212  -2.1488   1.6136 ]
 [-0.87625  0.73761  1.2978  -1.0145 ]
 [-4.8377  -4.2394   7.4592  -5.6012 ]]
The initial vector b 
 [ 2.8763 -3.3795 -2.1987 -1.2131]


The singular factorisation
U: 
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
S: 
 [[3.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.        ]
 [0.         0.         2.         0.        ]
 [0.         0.         0.         0.        ]]
V: 
 [[-0.          0.4472136  -0.          0.         -0.89442719]
 [ 0.          0.          1.          0.          0.        ]
 [ 1.          0.          0.          0.          0.        ]
 [-0.          0.         -0.          1.          0.        ]
 [ 0.          0.89442719  0.          0.          0.4472136 ]]


The rank of the matrix is 3


The conditional number of the matrix is 1.5


The solution of the simple system: Ax = 0


The solution of t